name: 'Deploy Swagger'

on:
  push

jobs:
  deploy-swagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run server in background
        run: npm run start:prod
      - name: Wait for server to start
        run: while ! curl --output /dev/null --silent --head --fail http://localhost:3000; do sleep 1; done
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-url: http://localhost:3000/api
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
